# Calls a workflow that builds a release.
name: Build Release

on:
  push:
    branches:
      - main
    tags:
      - '*'
      - '!**-alpha**'
    paths-ignore:
      - '.github/**'

jobs:
  package:
    name: Package Release
    uses: SFX-WoW/shared/.github/workflows/build-release.yml@main
