name: Pre-Release
on:
  push:
    tags:
      - '*.*.*-*'

jobs:
  package:
    name: Package Pre-Releases
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

    steps:
      - name: Clone Project
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: |
          sudo apt-get install luarocks pandoc
          luarocks install --local luacheck

      - name: Run LuaCheck
        run: /home/runner/.luarocks/bin/luacheck . -q

      - name: Package Release for Retail
        uses: BigWigsMods/packager@master

      - name: Package Release for Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g classic

      - name: Package Release for BC Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g bc
